name: covoiturage
description: "Application de covoiturage avec Flutter et Firebase"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  firebase_messaging: ^15.1.0

  # Carte et localisation
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  http: ^1.2.2

  # UI & Utilitaires
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/avatars/avatar_1.png
    - assets/avatars/avatar_2.png
    - assets/avatars/avatar_3.png
    - assets/avatars/avatar_4.png
    - assets/avatars/avatar_5.png
    - assets/avatars/avatar_6.png
    - assets/avatars/avatar_7.png
    - assets/avatars/avatar_8.png
    - assets/avatars/avatar_9.png
    - assets/avatars/avatar_10.png
    - assets/avatars/avatar_11.png
    - assets/avatars/avatar_12.png
    - assets/avatars/avatar_13.png
    - assets/avatars/avatar_14.png
    - assets/avatars/avatar_15.png
    - assets/avatars/avatar_16.png